### ISSUE TITLE
allow configuration with multi database sync 

### ISSUE THREAD

**Issue by maxlath** [ryanramage/couch2elastic4sync#10]
it would be awesome to be able to start sync on multiple databases like this:
```sh
couch2elastic4sync ./sync-config.json
```
with `sync-config.json` looking like:
```json
[
  {
    "couch": "http://localhost:5984/foo",
    "elastic": "http://localhost:9200/bar/foo"
  },
  {
    "couch": "http://localhost:5984/buzz",
    "elastic": "http://localhost:9200/bar/buzz"
  }
]
```
what do you think?

**Comment by ryanramage** [comment]
Hmm. I think that just starting two processes might be simpler, and cleaner when watching logs. etc.  Do you have a reason that you could not just start two different processes?

**Comment by maxlath** [comment]
can 2 processes be started with different rc configuration files? I see from the [documentation](https://www.npmjs.com/package/rc#standards) that rc can be passed a `--config file` parameter, but I guess that relies on a command line use of rc: how would you do that from the `couch2elastic4sync` command?

**Comment by ryanramage** [comment]
First, make sure couch2elastic4sync is install globally, so

    npm i couch2elastic4sync -g

then there are two ways. First, like you refer to, you can do the following

```
shell1$ couch2elastic4sync --config=sync1.json

shell2$ couch2elastic4sync --config=sync2.json
```

or you could have two directories with different .couch2elastic4sync files

```
shell1$ cd sync1; couch2elastic4sync;

shell2$ cd sync2; couch2elastic4sync;

```

**Comment by maxlath** [comment]
great!
