### ISSUE TITLE
Couch 2.0?

### ISSUE THREAD

**Issue by jbejar** [ryanramage/couch2elastic4sync#15]
I was unable to get this working with Couch 2.0 for a continuous sync. It creates a background process but doesn't sync. Has anyone else tried with 2.0?

**Comment by jbejar** [comment]
Actually the latest version worked, I just was using a Dockerfile that was pulling an old version... Sorry I left the other project a PR.
https://github.com/gesellix/couchdb-2-elasticsearch/pull/2

**Comment by ryanramage** [comment]
Ok great. thanks!
