### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by gesellix** [ryanramage/couch2elastic4sync#2]
This is less an issue, but more a try to discuss how one could prevent out of memory issues during initial `load` or a complete `sync` (w/ `since=0`).

Did you run into OOM errors in your setup? If so how did you tackle them? If not, would you have a spontaneous idea how to prevent such issues? I thought about modifying the code to work in batches instead of building a single stream. Would you also investigate in that direction?

Any ideas or suggestions are welcome :-)

**Comment by ryanramage** [comment]
I have not seen any memory errors on data sets I have been using, but so far the data I have used has been pretty small. Do you have a rough estimate of the number of docs you are loading? I could try and reproduce.

**Comment by gesellix** [comment]
here is the db metadata:

    "doc_count": 325865
    "update_seq": 435578

**Comment by ryanramage** [comment]
ok, I will give it a try it on a db of that size.

**Comment by gesellix** [comment]
great, thanks! If I can help/test anything for you, just ask.

**Comment by ryanramage** [comment]
Ok, @gesellix, I have made some improvements to the structure of the sync. I have not adjusted load just yet. But could you try out 3.2.0 version? Thanks!

**Comment by gesellix** [comment]
@ryanramage hey, thanks for continuing the work on it. I'll try probably on the weekend and give you feedback.

**Comment by ryanramage** [comment]
Closing this. Feel free to re-open!
